auto: true

markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important 
highlighter: rouge
anchorjs: true
permalink: pretty
paginate: 10

title: dhong.co
url: https://dhong.co
feed: /atom.xml
author_info: <a href="https://dhong.co/">Duan Hong</a>

# tags settings
featured-tags: true # wheather or not using feature-tags
featured-condition-size: 1 # A tag will be used if the size of it is more than this condition value

# google analytics settings
ga_track_id: 'UA-57346517-1' # format UA-xxxxxx-xx

# Disqus settings
disqus_username: dhong-co

# enable PWA
service_worker: true

# friends settings
friends: [{
    name: '阮一峰',
    link: 'http://www.ruanyifeng.com/blog/'
},{
    name: 'Hux',
    link: 'https://huangxuan.me'
},{
    name: '尹锋以为',
    link: 'http://ingf.github.io'
},{
    name: "Rocky",
    link: "http://rockywu.me/"
},{
    name: "Alvie",
    link: "http://alvie.net"
}]
