auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: dhong.co
url: http://dhong.co
feed: /atom.xml
author_info: <a href="http://dhong.co/">Duan Hong</a>

# tags settings
featured-tags: true # wheather or not using feature-tags
featured-condition-size: 1 # A tag will be used if the size of it is more than this condition value

# google analytics settings
ga_track_id: 'UA-57346517-1' # format UA-xxxxxx-xx

# Disqus settings
disqus_username: dhong-co

# friends settings
friends: [{
    name: '阮一峰',
    link: 'http://www.ruanyifeng.com/blog/'
},{
    name: 'Hux Blog',
    link: 'http://huangxuan.me'
},{
    name: '尹锋以为',
    link: 'http://ingf.github.io'
},{
    name: "Rocky's blog",
    link: "http://rockywu.me/"
},{
    name: "Alvie's Blog",
    link: "http://alvie.net"
},{
    name: "Leo Shang",
    link: "http://shangliuyan.github.io"
},{
    name: "Young Shook",
    link: "http://youngshook.com/"
}]
